/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bd.ClienteDAO;
import bd.DAOException;
import bd.ProdutoDAO;
import bd.VendaDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.Cliente;
import modelos.ItemVenda;
import modelos.Produto;
import modelos.Venda;

/**
 *
 * @author Lauren
 */
public class TelaRegistroVendas extends javax.swing.JFrame {

    private final ProdutoDAO produtoDAO;
    private final VendaDAO vendaDAO;
    private final ClienteDAO clienteDAO;

    private Cliente cliente;
    private Produto produtoA;
    private Produto produtoB;
    private Produto produtoC;
    private Produto produtoD;
    private Produto produtoE;
    private float precoTotal;

    /**
     * Creates new form TelaRegistroVendas
     */
    public TelaRegistroVendas() throws SQLException {
        initComponents();
        produtoDAO = new ProdutoDAO();
        vendaDAO = new VendaDAO();
        clienteDAO = new ClienteDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        lblIdCliente = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        lblIdProduto = new javax.swing.JLabel();
        lblDataDaVenda = new javax.swing.JLabel();
        lblRegistroVendas = new javax.swing.JLabel();
        lblquant = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        lblIdProduto3 = new javax.swing.JLabel();
        lblIdProduto2 = new javax.swing.JLabel();
        lblQuant3 = new javax.swing.JLabel();
        lblQuant2 = new javax.swing.JLabel();
        txtIdProduto2 = new javax.swing.JTextField();
        txtQuant2 = new javax.swing.JTextField();
        txtQuant3 = new javax.swing.JTextField();
        txtIdProduto3 = new javax.swing.JTextField();
        txtIdProduto4 = new javax.swing.JTextField();
        txtQuant4 = new javax.swing.JTextField();
        lblIdProduto4 = new javax.swing.JLabel();
        lblQuant4 = new javax.swing.JLabel();
        lblIdProduto5 = new javax.swing.JLabel();
        lblQuant5 = new javax.swing.JLabel();
        txtIdProduto5 = new javax.swing.JTextField();
        txtQuant5 = new javax.swing.JTextField();
        lblDescricaoProduto = new javax.swing.JLabel();
        lblDescricaoProduto2 = new javax.swing.JLabel();
        lblDescricaoProduto3 = new javax.swing.JLabel();
        lblDescricaoProduto4 = new javax.swing.JLabel();
        lblDescricaoProduto5 = new javax.swing.JLabel();
        txtDescricaoProduto5 = new javax.swing.JTextField();
        txtDescricaoProduto4 = new javax.swing.JTextField();
        txtDescricaoProduto3 = new javax.swing.JTextField();
        txtDescricaoProduto2 = new javax.swing.JTextField();
        txtDescricaoProduto = new javax.swing.JTextField();
        btnBuscarProduto1 = new javax.swing.JButton();
        btnBuscarProduto2 = new javax.swing.JButton();
        btnBuscarProduto3 = new javax.swing.JButton();
        btnBuscarProduto4 = new javax.swing.JButton();
        btnBuscarProduto5 = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtPreco2 = new javax.swing.JTextField();
        txtPreco3 = new javax.swing.JTextField();
        txtPreco4 = new javax.swing.JTextField();
        txtPreco5 = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        lblPreco2 = new javax.swing.JLabel();
        lblPreco3 = new javax.swing.JLabel();
        lblPreco4 = new javax.swing.JLabel();
        lblPreco5 = new javax.swing.JLabel();
        lblPrecoTotal = new javax.swing.JLabel();
        txtPrecoTotal = new javax.swing.JTextField();
        btnBuscarPrecoTotal = new javax.swing.JButton();
        txtDataDaVenda = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrar.setText("Registrar ");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblIdCliente.setText("ID do Cliente");

        lblIdProduto.setText("ID Produto");

        lblDataDaVenda.setText("Data da Venda");

        lblRegistroVendas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRegistroVendas.setText("REGISTRO VENDAS");

        lblquant.setText("Quant.");

        lblIdProduto3.setText("ID Produto 3");

        lblIdProduto2.setText("ID Produto 2");

        lblQuant3.setText("Quant. 3");

        lblQuant2.setText("Quant. 2");

        lblIdProduto4.setText("ID Produto 4");

        lblQuant4.setText("Quant. 4");

        lblIdProduto5.setText("ID Produto 5");

        lblQuant5.setText("Quant. 5");

        lblDescricaoProduto.setText("Descrição Produto");

        lblDescricaoProduto2.setText("Descrição Produto 2");

        lblDescricaoProduto3.setText("Descrição Produto 3");

        lblDescricaoProduto4.setText("Descrição Produto 4");

        lblDescricaoProduto5.setText("Descrição Produto 5");

        txtDescricaoProduto5.setEditable(false);
        txtDescricaoProduto5.setFocusable(false);

        txtDescricaoProduto4.setEditable(false);
        txtDescricaoProduto4.setFocusable(false);

        txtDescricaoProduto3.setEditable(false);
        txtDescricaoProduto3.setFocusable(false);

        txtDescricaoProduto2.setEditable(false);
        txtDescricaoProduto2.setFocusable(false);

        txtDescricaoProduto.setEditable(false);
        txtDescricaoProduto.setFocusable(false);

        btnBuscarProduto1.setText("Buscar");
        btnBuscarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProduto1ActionPerformed(evt);
            }
        });

        btnBuscarProduto2.setText("Buscar");
        btnBuscarProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProduto2ActionPerformed(evt);
            }
        });

        btnBuscarProduto3.setText("Buscar");
        btnBuscarProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProduto3ActionPerformed(evt);
            }
        });

        btnBuscarProduto4.setText("Buscar");
        btnBuscarProduto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProduto4ActionPerformed(evt);
            }
        });

        btnBuscarProduto5.setText("Buscar");
        btnBuscarProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProduto5ActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        txtCliente.setEditable(false);
        txtCliente.setFocusable(false);

        txtPreco.setEditable(false);
        txtPreco.setFocusable(false);

        txtPreco2.setEditable(false);
        txtPreco2.setFocusable(false);

        txtPreco3.setEditable(false);
        txtPreco3.setFocusable(false);

        txtPreco4.setEditable(false);
        txtPreco4.setFocusable(false);

        txtPreco5.setEditable(false);
        txtPreco5.setFocusable(false);

        lblPreco.setText("Preço");

        lblPreco2.setText("Preço 2");

        lblPreco3.setText("Preço 3 ");

        lblPreco4.setText("Preço 4");

        lblPreco5.setText("Preço 5");

        lblPrecoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecoTotal.setText("Valor Total");

        txtPrecoTotal.setEditable(false);
        txtPrecoTotal.setFocusable(false);

        btnBuscarPrecoTotal.setText("Calcular");
        btnBuscarPrecoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrecoTotalActionPerformed(evt);
            }
        });

        try {
            txtDataDaVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataDaVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdProduto5)
                            .addComponent(lblIdProduto4)
                            .addComponent(lblIdProduto3)
                            .addComponent(lblIdProduto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdProduto2)
                                    .addComponent(txtIdProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarProduto1)
                                    .addComponent(btnBuscarProduto5)
                                    .addComponent(btnBuscarProduto4)
                                    .addComponent(btnBuscarProduto3)
                                    .addComponent(btnBuscarProduto2)
                                    .addComponent(btnRegistrar))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPreco)
                                        .addGap(0, 51, Short.MAX_VALUE))
                                    .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescricaoProduto))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblquant)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpar)
                                .addGap(118, 118, 118))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtPreco3)
                            .addComponent(txtPreco2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPreco5)
                            .addComponent(lblPreco2)
                            .addComponent(lblPreco3)
                            .addComponent(lblPreco4)
                            .addComponent(txtPreco5))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescricaoProduto3)
                            .addComponent(lblDescricaoProduto2)
                            .addComponent(lblDescricaoProduto4)
                            .addComponent(lblDescricaoProduto5)
                            .addComponent(txtDescricaoProduto2)
                            .addComponent(txtDescricaoProduto3)
                            .addComponent(txtDescricaoProduto4)
                            .addComponent(txtDescricaoProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuant2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuant5)
                            .addComponent(lblQuant4)
                            .addComponent(lblQuant3)
                            .addComponent(txtQuant3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuant2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblRegistroVendas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrecoTotal)
                .addGap(18, 18, 18)
                .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBuscarPrecoTotal)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRegistroVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdCliente)
                    .addComponent(btnBuscarCliente)
                    .addComponent(lblDataDaVenda)
                    .addComponent(txtDataDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricaoProduto)
                                .addComponent(lblPreco))
                            .addComponent(lblquant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProduto1)
                            .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuant2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDescricaoProduto2)
                                .addComponent(lblPreco2)
                                .addComponent(lblIdProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProduto2)
                            .addComponent(txtIdProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuant3)
                            .addComponent(lblDescricaoProduto3)
                            .addComponent(lblPreco3)
                            .addComponent(lblIdProduto3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProduto3)
                            .addComponent(txtIdProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuant4)
                            .addComponent(lblDescricaoProduto4)
                            .addComponent(lblPreco4)
                            .addComponent(lblIdProduto4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProduto4)
                            .addComponent(txtIdProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuant5)
                            .addComponent(lblDescricaoProduto5)
                            .addComponent(lblPreco5)
                            .addComponent(lblIdProduto5))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuant5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricaoProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarProduto5)
                            .addComponent(txtIdProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoTotal)
                            .addComponent(btnBuscarPrecoTotal)))
                    .addComponent(lblIdProduto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        ArrayList<ItemVenda> itens = new ArrayList<>();
        String dataVenda = txtDataDaVenda.getText();
        
        if (produtoA != null && !txtQuant.getText().equals("")){
            ItemVenda item = new ItemVenda(produtoA, Integer.parseInt(txtQuant.getText()));
            itens.add(item);
        }
        if (produtoB != null && !txtQuant2.getText().equals("")){
            ItemVenda item = new ItemVenda(produtoB, Integer.parseInt(txtQuant2.getText()));
            itens.add(item);
        }
        if (produtoC != null && !txtQuant3.getText().equals("")){
            ItemVenda item = new ItemVenda(produtoC, Integer.parseInt(txtQuant3.getText()));
            itens.add(item);
        }
        if (produtoD != null && !txtQuant4.getText().equals("")){
            ItemVenda item = new ItemVenda(produtoD, Integer.parseInt(txtQuant4.getText()));
            itens.add(item);
        }
        if (produtoE != null && !txtQuant5.getText().equals("")){
            ItemVenda item = new ItemVenda(produtoE, Integer.parseInt(txtQuant5.getText()));
            itens.add(item);
        }
        
        if (txtDataDaVenda.getValue() != null && !itens.isEmpty() && cliente != null && precoTotal > 0) {
            try {
                Venda venda = new Venda(dataVenda, cliente, itens, precoTotal);
                vendaDAO.registrarVenda(venda);
                btnLimparActionPerformed(evt);
                JOptionPane.showMessageDialog(null, "Venda registrada com sucesso!");
            } catch (SQLException | DAOException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao registrar venda!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos e adicione pelo menos um produto!");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtIdProduto.setText(""); 
        produtoA = null; 
        txtDescricaoProduto.setText(""); 
        txtPreco.setText("");
        
        txtIdProduto2.setText(""); 
        produtoB = null; 
        txtDescricaoProduto2.setText(""); 
        txtPreco2.setText("");
        
        txtIdProduto3.setText(""); 
        produtoC = null; 
        txtDescricaoProduto3.setText(""); 
        txtPreco3.setText("");
        
        txtIdProduto4.setText(""); 
        produtoD = null; 
        txtDescricaoProduto4.setText(""); 
        txtPreco4.setText("");
        
        txtIdProduto5.setText(""); 
        produtoE = null; 
        txtDescricaoProduto5.setText(""); 
        txtPreco5.setText("");
        
        precoTotal = 0; 
        txtPrecoTotal.setText("");
        
        cliente = null; 
        txtCliente.setText(""); 
        txtIdCliente.setText("");
        
        txtDataDaVenda.setValue(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProduto1ActionPerformed
        try {
            if (!txtIdProduto.getText().equals("")) {
                produtoA = produtoDAO.buscarPorId(Integer.parseInt(txtIdProduto.getText()));
                if (produtoA == null) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                } else {
                    txtDescricaoProduto.setText(produtoA.toString());
                }
                txtPreco.setText(String.valueOf(produtoA.getPreco()));
            } else {
                JOptionPane.showMessageDialog(null, "Digite um id de produto");
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        }
    }//GEN-LAST:event_btnBuscarProduto1ActionPerformed

    private void btnBuscarProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProduto2ActionPerformed
        try {
            if (!txtIdProduto2.getText().equals("")) {
                produtoB = produtoDAO.buscarPorId(Integer.parseInt(txtIdProduto2.getText()));
                if (produtoB == null) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                } else {
                    txtDescricaoProduto2.setText(produtoB.toString());
                }
                txtPreco2.setText(String.valueOf(produtoB.getPreco()));
            } else {
                JOptionPane.showMessageDialog(null, "Digite um id de produto");
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        }
    }//GEN-LAST:event_btnBuscarProduto2ActionPerformed

    private void btnBuscarProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProduto3ActionPerformed
        try {
            if (!txtIdProduto3.getText().equals("")) {
                produtoC = produtoDAO.buscarPorId(Integer.parseInt(txtIdProduto3.getText()));
                if (produtoC == null) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                } else {
                    txtDescricaoProduto3.setText(produtoC.toString());
                }
                txtPreco3.setText(String.valueOf(produtoC.getPreco()));
            } else {
                JOptionPane.showMessageDialog(null, "Digite um id de produto");
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        }
    }//GEN-LAST:event_btnBuscarProduto3ActionPerformed

    private void btnBuscarProduto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProduto4ActionPerformed
        try {
            if (!txtIdProduto4.getText().equals("")) {
                produtoD = produtoDAO.buscarPorId(Integer.parseInt(txtIdProduto4.getText()));
                if (produtoD == null) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                } else {
                    txtDescricaoProduto4.setText(produtoD.toString());
                }
                txtPreco4.setText(String.valueOf(produtoD.getPreco()));
            } else {
                JOptionPane.showMessageDialog(null, "Digite um id de produto");
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        }
    }//GEN-LAST:event_btnBuscarProduto4ActionPerformed

    private void btnBuscarProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProduto5ActionPerformed
        try {
            if (!txtIdProduto5.getText().equals("")) {
                produtoE = produtoDAO.buscarPorId(Integer.parseInt(txtIdProduto5.getText()));
                if (produtoE == null) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                } else {
                    txtDescricaoProduto5.setText(produtoE.toString());
                }
                txtPreco5.setText(String.valueOf(produtoE.getPreco()));
            } else {
                JOptionPane.showMessageDialog(null, "Digite um id de produto");
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        }
    }//GEN-LAST:event_btnBuscarProduto5ActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        try {
            if (!txtIdCliente.getText().equals("")) {
                cliente = clienteDAO.buscarPorId(Integer.parseInt(txtIdCliente.getText()));
                if (cliente == null) {
                    JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
                } else {
                    txtCliente.setText(cliente.toString());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite um id de cliente");
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarPrecoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrecoTotalActionPerformed
        precoTotal = 0;

        if (produtoA != null && !txtQuant.getText().equals(""))
            precoTotal = precoTotal + (produtoA.getPreco() * Integer.parseInt(txtQuant.getText()));
        if (produtoB != null && !txtQuant2.getText().equals(""))
            precoTotal = precoTotal + (produtoB.getPreco() * Integer.parseInt(txtQuant2.getText()));
        if (produtoC != null && !txtQuant3.getText().equals(""))
            precoTotal = precoTotal + (produtoC.getPreco() * Integer.parseInt(txtQuant3.getText()));
        if (produtoD != null && !txtQuant4.getText().equals(""))
            precoTotal = precoTotal + (produtoC.getPreco() * Integer.parseInt(txtQuant4.getText()));
        if (produtoE != null && !txtQuant5.getText().equals(""))
            precoTotal = precoTotal + (produtoC.getPreco() * Integer.parseInt(txtQuant5.getText()));

        txtPrecoTotal.setText(String.valueOf(precoTotal));
    }//GEN-LAST:event_btnBuscarPrecoTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaRegistroVendas().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro no banco de dados!");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarPrecoTotal;
    private javax.swing.JButton btnBuscarProduto1;
    private javax.swing.JButton btnBuscarProduto2;
    private javax.swing.JButton btnBuscarProduto3;
    private javax.swing.JButton btnBuscarProduto4;
    private javax.swing.JButton btnBuscarProduto5;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblDataDaVenda;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblDescricaoProduto2;
    private javax.swing.JLabel lblDescricaoProduto3;
    private javax.swing.JLabel lblDescricaoProduto4;
    private javax.swing.JLabel lblDescricaoProduto5;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblIdProduto2;
    private javax.swing.JLabel lblIdProduto3;
    private javax.swing.JLabel lblIdProduto4;
    private javax.swing.JLabel lblIdProduto5;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblPreco3;
    private javax.swing.JLabel lblPreco4;
    private javax.swing.JLabel lblPreco5;
    private javax.swing.JLabel lblPrecoTotal;
    private javax.swing.JLabel lblQuant2;
    private javax.swing.JLabel lblQuant3;
    private javax.swing.JLabel lblQuant4;
    private javax.swing.JLabel lblQuant5;
    private javax.swing.JLabel lblRegistroVendas;
    private javax.swing.JLabel lblquant;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtDataDaVenda;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtDescricaoProduto2;
    private javax.swing.JTextField txtDescricaoProduto3;
    private javax.swing.JTextField txtDescricaoProduto4;
    private javax.swing.JTextField txtDescricaoProduto5;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtIdProduto2;
    private javax.swing.JTextField txtIdProduto3;
    private javax.swing.JTextField txtIdProduto4;
    private javax.swing.JTextField txtIdProduto5;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPreco2;
    private javax.swing.JTextField txtPreco3;
    private javax.swing.JTextField txtPreco4;
    private javax.swing.JTextField txtPreco5;
    private javax.swing.JTextField txtPrecoTotal;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtQuant2;
    private javax.swing.JTextField txtQuant3;
    private javax.swing.JTextField txtQuant4;
    private javax.swing.JTextField txtQuant5;
    // End of variables declaration//GEN-END:variables
}
