/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bd.DAOException;
import bd.VendaDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Venda;

/**
 *
 * @author Lauren
 */
public class TelaRelatorioVendas extends javax.swing.JFrame {

    private final VendaDAO vendaDAO;

    /**
     * Creates new form TelaRelatorioVendas
     */
    public TelaRelatorioVendas() throws DAOException, SQLException {
        vendaDAO = new VendaDAO();
        initComponents();
        populateTblRelatorioVendas();
    }

    private void populateTblRelatorioVendas() {
        try {
            ((DefaultTableModel) tblRelatorioVendas.getModel()).setRowCount(0);
            ArrayList<Venda> vendas  = vendaDAO.buscar();
            for (Venda venda : vendas) {
                Object[] objs = {venda.getIdVenda(), venda.getCliente().getNome(),
                    venda.getDataVenda(), venda.getPrecoTotal()
                };
                ((DefaultTableModel) tblRelatorioVendas.getModel()).addRow(objs);
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o Banco de dados!");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorioVendas = new javax.swing.JTable();
        btnAtualizarVendas = new javax.swing.JButton();
        lblRelatorioVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRelatorioVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Data da Venda", "Total da Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRelatorioVendas);
        if (tblRelatorioVendas.getColumnModel().getColumnCount() > 0) {
            tblRelatorioVendas.getColumnModel().getColumn(0).setMaxWidth(40);
            tblRelatorioVendas.getColumnModel().getColumn(1).setMinWidth(100);
            tblRelatorioVendas.getColumnModel().getColumn(2).setMinWidth(100);
            tblRelatorioVendas.getColumnModel().getColumn(2).setMaxWidth(100);
            tblRelatorioVendas.getColumnModel().getColumn(3).setMinWidth(100);
            tblRelatorioVendas.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        btnAtualizarVendas.setText("Atualizar");
        btnAtualizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarVendasActionPerformed(evt);
            }
        });

        lblRelatorioVendas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRelatorioVendas.setText("RELATORIO VENDAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAtualizarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblRelatorioVendas)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblRelatorioVendas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarVendasActionPerformed
        populateTblRelatorioVendas();
    }//GEN-LAST:event_btnAtualizarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaRelatorioVendas().setVisible(true);
                } catch (DAOException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao conectar no banco de dados!");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRelatorioVendas;
    private javax.swing.JTable tblRelatorioVendas;
    // End of variables declaration//GEN-END:variables

}
