/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bd.DAOException;
import bd.EstoqueEntradaDAO;
import bd.ProdutoDAO;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.EstoqueEntrada;
import modelos.EstoqueSaida;
import modelos.Produto;

/**
 *
 * @author Lauren
 */
public class TelaEstoqueEntrada extends javax.swing.JFrame {
    
    private final EstoqueEntradaDAO estoqueEntradaDAO;
    private final ProdutoDAO produtoDAO;
    
    private Produto produtoSelecionado;

    /**
     * Creates new form TelaCadastroEstoque
     *
     * @throws java.sql.SQLException
     */
    public TelaEstoqueEntrada() throws DAOException, SQLException {
        initComponents();
        estoqueEntradaDAO = new EstoqueEntradaDAO();
        produtoDAO = new ProdutoDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroEstoqueEntrada = new javax.swing.JLabel();
        txtIdProdutoEntrada = new javax.swing.JTextField();
        lblIdProdutoEntrada = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtProdutoSelecionado = new javax.swing.JTextField();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        lblDataEntrada = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidadeEstoque = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastroEstoqueEntrada.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCadastroEstoqueEntrada.setText("ENTRADA DE ESTOQUE");

        lblIdProdutoEntrada.setText("Id Produto");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtProdutoSelecionado.setEditable(false);
        txtProdutoSelecionado.setFocusable(false);

        try {
            txtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDataEntrada.setText("Data de entrada");

        lblQuantidade.setText("Quantidade");

        btnSalvar.setText("Registrar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(72, Short.MAX_VALUE)
                        .addComponent(lblCadastroEstoqueEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantidade)
                                    .addComponent(txtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataEntrada)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar))
                                    .addComponent(lblIdProdutoEntrada))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtProdutoSelecionado))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCadastroEstoqueEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblIdProdutoEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(txtIdProdutoEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtProdutoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblDataEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpar() {
        txtIdProdutoEntrada.setText("");
        txtProdutoSelecionado.setText("");
        txtDataEntrada.setValue(null);
        txtQuantidadeEstoque.setText("");
        produtoSelecionado = null;
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String produto = txtIdProdutoEntrada.getText();
        String quantidade = txtQuantidadeEstoque.getText();
        String dataSaida = txtDataEntrada.getText();
        if (produtoSelecionado != null && !quantidade.equals("") && !dataSaida.equals("")) {
            try {
                EstoqueEntrada e = new EstoqueEntrada(produtoSelecionado, Integer.parseInt(quantidade), dataSaida);
                this.estoqueEntradaDAO.incluir(e);
                JOptionPane.showMessageDialog(null, "Entrada de estoque cadastrada com sucesso!");
                limpar();
            } catch (DAOException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar entrada de estoque!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os dados!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int idProduto = Integer.parseInt(txtIdProdutoEntrada.getText());
            Produto p = produtoDAO.buscarPorId(idProduto);
            if (p != null) {
                txtProdutoSelecionado.setText(p.toString());
                produtoSelecionado = p;
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                txtProdutoSelecionado.setText("");
                produtoSelecionado = null;
            }
        } catch (DAOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaEstoqueEntrada().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco de dados!");
                } catch (DAOException ex) {
                    Logger.getLogger(TelaEstoqueEntrada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCadastroEstoqueEntrada;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblIdProdutoEntrada;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JTextField txtIdProdutoEntrada;
    private javax.swing.JTextField txtProdutoSelecionado;
    private javax.swing.JTextField txtQuantidadeEstoque;
    // End of variables declaration//GEN-END:variables
}
