/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bd.DAOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lauren
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private final TelaEstoqueSaida telaCadastroEstoqueSaida;
    private final TelaCadastroFornecedor telaCadastroFornecedor;
    private final TelaEstoqueEntrada telaCadastroEstoque;
    private final TelaCadastroCliente telaCadastroCliente;
    private final TelaCadastroProduto telaCadastroProduto;
    private final TelaRegistroVendas telaRegistroVendas;
    private final TelaRelatorioCliente telaRelatorioCliente;
    private final TelaRelatorioFornecedor telaRelatorioFornecedor;
    private final TelaRelatorioProdutosDisponiveis telaRelatorioProdutos;
    private final TelaRelatorioProdutoSaida telaRelatorioProdutoSaida;
    private final TelaRelatorioVendas telaRelatorioVendas;
    private final TelaEstoque telaEstoque;
    private final TelaEstoqueSaida telaEstoqueSaida;
    
    /**
     * Creates new form FrameModulos
     * @throws java.sql.SQLException
     */
    public TelaPrincipal() throws SQLException, DAOException{
        initComponents(); 
        this.telaCadastroEstoqueSaida = new TelaEstoqueSaida();
        this.telaCadastroFornecedor = new TelaCadastroFornecedor();
        this.telaCadastroEstoque = new TelaEstoqueEntrada();
        this.telaCadastroCliente = new TelaCadastroCliente();
        this.telaCadastroProduto = new TelaCadastroProduto();
        this.telaRegistroVendas = new TelaRegistroVendas();
        this.telaRelatorioCliente = new TelaRelatorioCliente();
        this.telaRelatorioFornecedor = new TelaRelatorioFornecedor();
        this.telaRelatorioProdutos = new TelaRelatorioProdutosDisponiveis();
        this.telaRelatorioProdutoSaida = new TelaRelatorioProdutoSaida();
        this.telaRelatorioVendas  = new TelaRelatorioVendas();
        this.telaEstoque = new TelaEstoque();
        this.telaEstoqueSaida = new TelaEstoqueSaida();
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        painelCentral = new javax.swing.JPanel();
        imagemDeFundo = new javax.swing.JLabel();
        barraDeMenus = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        btnCadastroProduto = new javax.swing.JMenuItem();
        btnCadastroCliente = new javax.swing.JMenuItem();
        btnCadastroFornecedor = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnEstoqueEntrada = new javax.swing.JMenuItem();
        btnEstoqueSaida = new javax.swing.JMenuItem();
        btnVisualizarEstoque = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        btnListaFornecedor = new javax.swing.JMenuItem();
        btnRelatorioVendas = new javax.swing.JMenuItem();
        btnProdutosDisponiveis = new javax.swing.JMenuItem();
        btnProdutosVendidos = new javax.swing.JMenuItem();
        btnVendas = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        btnRegistrarVenda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout painelCentralLayout = new javax.swing.GroupLayout(painelCentral);
        painelCentral.setLayout(painelCentralLayout);
        painelCentralLayout.setHorizontalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCentralLayout.createSequentialGroup()
                .addContainerGap(585, Short.MAX_VALUE)
                .addComponent(imagemDeFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelCentralLayout.setVerticalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCentralLayout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(imagemDeFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuCadastros.setText("Cadastros");

        btnCadastroProduto.setText("Cadastro Produto");
        btnCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastros.add(btnCadastroProduto);

        btnCadastroCliente.setText("Cadastro Cliente");
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(btnCadastroCliente);

        btnCadastroFornecedor.setText("Cadastro Fornecedor");
        btnCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFornecedorActionPerformed(evt);
            }
        });
        menuCadastros.add(btnCadastroFornecedor);

        barraDeMenus.add(menuCadastros);

        jMenu1.setText("Estoque");

        btnEstoqueEntrada.setText("Nova Entrada");
        btnEstoqueEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(btnEstoqueEntrada);

        btnEstoqueSaida.setText("Nova Saida");
        btnEstoqueSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueSaidaActionPerformed(evt);
            }
        });
        jMenu1.add(btnEstoqueSaida);

        btnVisualizarEstoque.setText("Visualizar Estoque");
        btnVisualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarEstoqueActionPerformed(evt);
            }
        });
        jMenu1.add(btnVisualizarEstoque);

        barraDeMenus.add(jMenu1);

        menuRelatorios.setText("Relatórios");

        btnListaFornecedor.setText("Lista de Clientes");
        btnListaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaFornecedorActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnListaFornecedor);

        btnRelatorioVendas.setText("Lista de Fornecedores");
        btnRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnRelatorioVendas);

        btnProdutosDisponiveis.setText("Lista de Produtos Disponíveis");
        btnProdutosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosDisponiveisActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnProdutosDisponiveis);

        btnProdutosVendidos.setText("Lista de Saida de Estoque");
        btnProdutosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosVendidosActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnProdutosVendidos);

        btnVendas.setText("Lista de Vendas");
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnVendas);

        barraDeMenus.add(menuRelatorios);

        menuOpcoes.setText("Vendas");

        btnRegistrarVenda.setText("Registrar Venda");
        btnRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVendaActionPerformed(evt);
            }
        });
        menuOpcoes.add(btnRegistrarVenda);

        barraDeMenus.add(menuOpcoes);

        setJMenuBar(barraDeMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioVendasActionPerformed
        this.telaRelatorioFornecedor.setLocationRelativeTo (null);
        this.telaRelatorioFornecedor.setVisible(true);
        this.telaRelatorioFornecedor.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnRelatorioVendasActionPerformed
        
    private void btnCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFornecedorActionPerformed
        this.telaCadastroFornecedor.setLocationRelativeTo(null);
        this.telaCadastroFornecedor.setVisible(true);
        this.telaCadastroFornecedor.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnCadastroFornecedorActionPerformed

    private void btnEstoqueSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueSaidaActionPerformed
        this.telaCadastroEstoqueSaida.setLocationRelativeTo(null);
        this.telaCadastroEstoqueSaida.setVisible(true);
        this.telaCadastroEstoqueSaida.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnEstoqueSaidaActionPerformed

    private void btnEstoqueEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueEntradaActionPerformed
        this.telaCadastroEstoque.setLocationRelativeTo(null);
        this.telaCadastroEstoque.setVisible(true);
        this.telaCadastroEstoque.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnEstoqueEntradaActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        this.telaCadastroCliente.setLocationRelativeTo(null);
        this.telaCadastroCliente.setVisible(true);
        this.telaCadastroCliente.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed
        this.telaCadastroProduto.setLocationRelativeTo(null);
        this.telaCadastroProduto.setVisible(true);
        this.telaCadastroProduto.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    private void btnRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVendaActionPerformed
        this.telaRegistroVendas.setLocationRelativeTo(null);
        this.telaRegistroVendas.setVisible(true);
        this.telaRegistroVendas.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnRegistrarVendaActionPerformed

    private void btnListaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaFornecedorActionPerformed
        this.telaRelatorioCliente.setLocationRelativeTo(null);
        this.telaRelatorioCliente.setVisible(true);
        this.telaRelatorioCliente.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnListaFornecedorActionPerformed

    private void btnProdutosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosDisponiveisActionPerformed
        this.telaRelatorioProdutos.setLocationRelativeTo(null);
        this.telaRelatorioProdutos.setVisible(true);
        this.telaRelatorioProdutos.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnProdutosDisponiveisActionPerformed

    private void btnProdutosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosVendidosActionPerformed
        this.telaRelatorioProdutoSaida.setLocationRelativeTo(null);
        this.telaRelatorioProdutoSaida.setVisible(true);
        this.telaRelatorioProdutoSaida.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnProdutosVendidosActionPerformed

    private void btnVisualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarEstoqueActionPerformed
        this.telaEstoque.setLocationRelativeTo(null);                                                   
        this.telaEstoque.setVisible(true);                                                 
        this.telaEstoque.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnVisualizarEstoqueActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        this.telaRelatorioVendas.setLocationRelativeTo(null);
        this.telaRelatorioVendas.setVisible(true);
        this.telaRelatorioVendas.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            TelaPrincipal telaPrincipal;
            try {
                telaPrincipal = new TelaPrincipal();
                telaPrincipal.setLocationRelativeTo(null);
                telaPrincipal.setVisible(true);
            } catch (SQLException | DAOException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar acessos ao banco!");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenus;
    private javax.swing.JMenuItem btnCadastroCliente;
    private javax.swing.JMenuItem btnCadastroFornecedor;
    private javax.swing.JMenuItem btnCadastroProduto;
    private javax.swing.JMenuItem btnEstoqueEntrada;
    private javax.swing.JMenuItem btnEstoqueSaida;
    private javax.swing.JMenuItem btnListaFornecedor;
    private javax.swing.JMenuItem btnProdutosDisponiveis;
    private javax.swing.JMenuItem btnProdutosVendidos;
    private javax.swing.JMenuItem btnRegistrarVenda;
    private javax.swing.JMenuItem btnRelatorioVendas;
    private javax.swing.JMenuItem btnVendas;
    private javax.swing.JMenuItem btnVisualizarEstoque;
    private javax.swing.JLabel imagemDeFundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JPanel painelCentral;
    // End of variables declaration//GEN-END:variables

}
